### ISSUE TITLE
maven-scm-provider-svnjava don't include the license file

### ISSUE THREAD

**Issue by puntogil** [olamy/maven-scm-provider-svnjava#16]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by olamy** [comment]
fixed.
Thanks for reporting!
