### ISSUE TITLE
Use SLF4J instead of SCM Logger

### ISSUE THREAD

**Issue by longbeach** [olamy/maven-scm-provider-svnjava#55]
### What feature do you want to see added?

Hello, we would like to use the maven-release-plugin plugin (version 3.0.0-M7) with the latest maven-scm-provider-svnjava version.

 ```
<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>3.0.0-M7</version>
          <configuration>
            <autoVersionSubmodules>true</autoVersionSubmodules>
            <preparationGoals>clean package</preparationGoals>
            <tagBase>${svnssh.url}/${svn.tagspath}</tagBase>
            <providerImplementations>
                <svn>javasvn</svn>
                <git>jgit</git>
            </providerImplementations>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>com.google.code.maven-scm-provider-svnjava</groupId>
              <artifactId>maven-scm-provider-svnjava</artifactId>
              <version>2.2.1</version>
            </dependency>
            <dependency>
              <groupId>org.apache.maven.scm</groupId>
              <artifactId>maven-scm-provider-jgit</artifactId>
              <version>2.0.0-M3</version>
            </dependency>
          </dependencies>
</plugin>      
``` 

Unfortunately it fails : 
_org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.0-M7:prepare (default-cli) on project vie: Execution default-cli of goal org.apache.maven.plugins:maven-release-plugin:3.0.0-M7:prepare failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-release-plugin:3.0.0-M7:prepare: java.lang.NoSuchMethodError: org.apache.maven.scm.provider.svn.svnjava.command.status.SvnJavaStatusCommand.getLogger()Lorg/apache/maven/scm/log/ScmLogger;_

Indeed SCM Logger was dropped in favor of SLF4J : 
https://github.com/apache/maven-scm/commit/1f6d1281a058d3cf917fdc8e26d079e4d0c5a2b5

Are you planning on switching to SLF4J soon and so upgrading the version of maven-scm-provider-svn-commons (1.12.2 => 2.0.0-M3) ?
I can pull a request to work on it but i need your opinion first.
Thanks

**Comment by olamy** [comment]
Hi
Feel free to create a pull request.
I will definitely review and merge it.
Thanks
